export const PORTALS = [
  {
    id: 'production-orders',
    name: 'Production Orders',
    icon: 'assignment',
    color: '#0891B2',
    desc: 'Work orders, BOM allocation, scheduling & dispatch',
    path: 'production-orders',
    roles: ['super_admin', 'plant_head', 'production_mgr', 'planner', 'supervisor'],
  },
  {
    id: 'shop-floor',
    name: 'Shop Floor',
    icon: 'factory',
    color: '#7C3AED',
    desc: 'Real-time machine status, operator logs, line output',
    path: 'shop-floor',
    roles: ['super_admin', 'plant_head', 'production_mgr', 'supervisor', 'operator'],
  },
  {
    id: 'quality',
    name: 'Quality Control',
    icon: 'verified',
    color: '#DC2626',
    desc: 'Inspection, NCR/CAPA, SPC charts, audit tracking',
    path: 'quality',
    roles: ['super_admin', 'plant_head', 'quality_mgr', 'quality_inspector', 'supervisor'],
  },
  {
    id: 'cnc-machining',
    name: 'CNC & Machining',
    icon: 'precision_manufacturing',
    color: '#B45309',
    desc: 'CNC programs, tool life, cycle times, setup sheets',
    path: 'cnc-machining',
    roles: ['super_admin', 'plant_head', 'production_mgr', 'cnc_lead', 'operator'],
  },
  {
    id: 'assembly',
    name: 'Assembly',
    icon: 'construction',
    color: '#059669',
    desc: 'Assembly stations, torque logs, leak test, final build',
    path: 'assembly',
    roles: ['super_admin', 'plant_head', 'production_mgr', 'assembly_lead', 'operator'],
  },
  {
    id: 'paint-coating',
    name: 'Paint & Coating',
    icon: 'format_paint',
    color: '#C026D3',
    desc: 'Paint booth scheduling, coating thickness, curing logs',
    path: 'paint-coating',
    roles: ['super_admin', 'plant_head', 'production_mgr', 'paint_lead', 'operator'],
  },
  {
    id: 'welding',
    name: 'Welding',
    icon: 'bolt',
    color: '#EA580C',
    desc: 'Weld parameters, WPS tracking, welder qualification',
    path: 'welding',
    roles: ['super_admin', 'plant_head', 'production_mgr', 'welding_lead', 'operator'],
  },
  {
    id: 'testing',
    name: 'Testing & Validation',
    icon: 'labs',
    color: '#4F46E5',
    desc: 'Performance tests, endurance runs, test certificates',
    path: 'testing',
    roles: ['super_admin', 'plant_head', 'quality_mgr', 'test_engineer', 'supervisor'],
  },
  {
    id: 'maintenance',
    name: 'Maintenance',
    icon: 'build',
    color: '#B91C1C',
    desc: 'PM schedules, breakdown log, spare parts, MTBF',
    path: 'maintenance',
    roles: ['super_admin', 'plant_head', 'maintenance_mgr', 'maintenance_tech', 'supervisor'],
  },
  {
    id: 'material-wip',
    name: 'Material & WIP',
    icon: 'inventory_2',
    color: '#0D9488',
    desc: 'Raw material tracking, WIP stages, inter-shop transfers',
    path: 'material-wip',
    roles: ['super_admin', 'plant_head', 'production_mgr', 'store_keeper', 'planner'],
  },
  {
    id: 'shift-mgmt',
    name: 'Shift Management',
    icon: 'schedule',
    color: '#9333EA',
    desc: 'Shift rosters, attendance, overtime, handover notes',
    path: 'shift-mgmt',
    roles: ['super_admin', 'plant_head', 'production_mgr', 'hr_mgr', 'supervisor'],
  },
  {
    id: 'reports',
    name: 'Reports & Analytics',
    icon: 'analytics',
    color: '#64748B',
    desc: 'Daily production reports, OEE trends, management dashboards',
    path: 'reports',
    roles: ['super_admin', 'plant_head', 'production_mgr', 'quality_mgr', 'planner'],
  },
];

export const ROLES = {
  super_admin:      { label: 'Super Admin',        level: 0 },
  plant_head:       { label: 'Plant Head',          level: 1 },
  production_mgr:   { label: 'Production Manager',  level: 2 },
  quality_mgr:      { label: 'Quality Manager',     level: 2 },
  maintenance_mgr:  { label: 'Maintenance Manager', level: 2 },
  hr_mgr:           { label: 'HR Manager',          level: 2 },
  planner:          { label: 'Production Planner',  level: 3 },
  supervisor:       { label: 'Shift Supervisor',    level: 3 },
  cnc_lead:         { label: 'CNC Section Lead',    level: 3 },
  assembly_lead:    { label: 'Assembly Lead',       level: 3 },
  paint_lead:       { label: 'Paint Section Lead',  level: 3 },
  welding_lead:     { label: 'Welding Lead',        level: 3 },
  quality_inspector:{ label: 'Quality Inspector',   level: 4 },
  test_engineer:    { label: 'Test Engineer',       level: 4 },
  maintenance_tech: { label: 'Maintenance Tech',    level: 4 },
  store_keeper:     { label: 'Store Keeper',        level: 4 },
  operator:         { label: 'Operator',            level: 5 },
};
